Repository mohsinshah04/ta_project, pull requests merged in 2024-04, with the labels that each got.

#18 Database Created, Prelimary Changes For Project As Well
  djangoProject1/djangoProject1/settings.py
  djangoProject1/djangoProject1/urls.py
  djangoProject1/ta_app/admin.py
  djangoProject1/ta_app/migrations/0001_initial.py
  djangoProject1/ta_app/models.py
  djangoProject1/ta_app/views.py
Labels: bug, enhancement, help wanted

#20 templates and got text on home page got rid of error
  djangoProject1/ta_app/views.py
  djangoProject1/templates/accounts.html
  djangoProject1/templates/acctCreate.html
  djangoProject1/templates/acctsEdit.html
  djangoProject1/templates/acctsOtherEdit.html
  djangoProject1/templates/announcements.html
  djangoProject1/templates/courseCreate.html
  djangoProject1/templates/courseEdit.html
  djangoProject1/templates/courseView.html
  djangoProject1/templates/home.html
  djangoProject1/templates/loggedOutPage.html
  djangoProject1/templates/loginPage.html
  djangoProject1/templates/sectionCreate.html
  djangoProject1/templates/sectionEdit.html
  djangoProject1/templates/sectionView.html
Labels: enhancement

#24 Bleon- Database updates and bug fixes
  .idea/ta_project.iml
  djangoProject1/ta_app/admin.py
  djangoProject1/ta_app/migrations/0002_user_user_phone_number_alter_user_user_home_address.py
  djangoProject1/ta_app/migrations/0003_alter_user_user_email_alter_user_user_fname_and_more.py
  djangoProject1/ta_app/migrations/0004_alter_assign_user_junction_section_id.py
  djangoProject1/ta_app/migrations/0005_alter_assign_user_junction_section_id.py
  djangoProject1/ta_app/models.py
Labels: enhancement

#35 Mock Object and Cgances
  .idea/misc.xml
  .idea/ta_project.iml
  djangoProject1/__init__.py
  djangoProject1/classes/CourseClass.py
  djangoProject1/classes/UserAbstractClass.py
  djangoProject1/ta_app/migrations/0001_initial.py
  djangoProject1/ta_app/migrations/0002_user_user_phone_number_alter_user_user_home_address.py
  djangoProject1/ta_app/migrations/0003_alter_user_user_email_alter_user_user_fname_and_more.py
  djangoProject1/ta_app/migrations/0004_alter_assign_user_junction_section_id.py
  djangoProject1/ta_app/migrations/0005_alter_assign_user_junction_section_id.py
  djangoProject1/ta_app/migrations/0006_user_user_id.py
  djangoProject1/ta_app/models.py
  djangoProject1/ta_app/tests/__init__.py
  djangoProject1/tests/mocks.py
  djangoProject1/tests/test_AbstractUser.py
  djangoProject1/tests/test_Course.py
Labels: help wanted, good first issue, question

#37 Created Mock Object and Course Unit tests
  djangoProject1/tests/mocks.py
  djangoProject1/tests/test_Course.py
Labels: enhancement

#44 views and urls,
  djangoProject1/djangoProject1/urls.py
  djangoProject1/ta_app/views.py
  djangoProject1/templates/acctsCreate.html
  djangoProject1/templates/acctsView.html
  djangoProject1/templates/home.html
  djangoProject1/templates/logOutPage.html
Labels: enhancement

#45 finished connecting all urls and have all pages linking to one another as in the design
  djangoProject1/djangoProject1/urls.py
  djangoProject1/templates/acctsCreate.html
  djangoProject1/templates/acctsEdit.html
  djangoProject1/templates/acctsOtherEdit.html
  djangoProject1/templates/acctsView.html
  djangoProject1/templates/announcements.html
  djangoProject1/templates/courseCreate.html
  djangoProject1/templates/courseEdit.html
  djangoProject1/templates/courseView.html
  djangoProject1/templates/home.html
  djangoProject1/templates/loginPage.html
  djangoProject1/templates/sectionCreate.html
  djangoProject1/templates/sectionEdit.html
  djangoProject1/templates/sectionView.html
Labels: enhancement

#47 Design Changes, re-do testing, added tests, Course implmentation redid
  djangoProject1/classes/CourseClass.py
  djangoProject1/classes/UserClass.py
  djangoProject1/tests/mocks.py
  djangoProject1/tests/test_Course.py
Labels: enhancement

#53 Semester Tests And implmenation
  djangoProject1/classes/SemesterClass.py
  djangoProject1/tests_UnitTests/test_Semester.py
Labels: enhancement

#62 Course Side of things compelted, ready to merge
  djangoProject1/classes/CourseClass.py
  djangoProject1/classes/SemesterClass.py
  djangoProject1/djangoProject1/settings.py
  djangoProject1/ta_app/views.py
  djangoProject1/templates/courseCreate.html
  djangoProject1/templates/courseEdit.html
  djangoProject1/templates/courseView.html
  djangoProject1/templates/home.html
  djangoProject1/tests_AcceptanceTests/test_Courses.py
Labels: enhancement

#66 adjusted css(test)
  djangoProject1/templates/home.html
Labels: enhancement

#76 fixed login message
  djangoProject1/ta_app/views.py
  djangoProject1/templates/acctsViewSelf.html
Labels: enhancement

#80 finished takss and refined css and html
  djangoProject1/ta_app/views.py
  djangoProject1/templates/acctsCreate.html
  djangoProject1/templates/acctsOtherEdit.html
  djangoProject1/templates/acctsView.html
  djangoProject1/templates/acctsViewSelf.html
Labels: enhancement

#87 fixed the table and created page redirects
  djangoProject1/djangoProject1/urls.py
  djangoProject1/ta_app/views.py
  djangoProject1/templates/acctsView.html
  djangoProject1/templates/courseViewTA_IN.html
Labels: enhancement
